### ISSUE TITLE
Interested in releasing a snap package?

### ISSUE THREAD

**Issue by daPhipz** [bit101/version#15]
Are you interested in releasing `version` as a snap? I would love to implement the necessary code as sort of a coding exercise ;)
If you don't want to deal with maintaining the snap and upload every new version to the snap store, I could also do all that on my fork and pull all changes in from here - if that's ok of course.

**Comment by bit101** [comment]
Yes, very interested. I'd love to learn more about it. Maybe it could be put in a github action?

**Comment by daPhipz** [comment]
Yes, that was my idea!
We could implement an action that automatically builds a snap package whenever a tag is pushed to the GitHub repo. If you don't mind, I'll have a look at that tomorrow!

**Comment by daPhipz** [comment]
Maybe you could create a separate feature branch for the snap code, so we can push to that and don't disturb the rest of the project. That way, we can both work collaboratively and merge into master when everything is ready.

**Comment by bit101** [comment]
https://github.com/bit101/version/tree/snap
