### ISSUE TITLE
Wrap around package managers to support way more packages.

### ISSUE THREAD

**Issue by bionade24** [bit101/version#33]
Instead of relying on existing command line utilities for program and only index a small amount in a list, just detect the Linux/Mac version and wrap around the package managers (pacman/apt/dnf/brew) to support libs and things without a version option in the binary, too.

**Comment by daPhipz** [comment]
Doni understand this correctly?
Instead of identifying the version through a flag or something similar, you want to search the distro's package manager to retrieve the version it provides.

Pro:
- 1. Practically any package can be displayed that way.

Caveat:
- 1. We should use this method only as backup if other methods fail, since it doesn't necessarily show the version of the actually installed package (e.g. user hasn't done an upgrade recently). Additionally, a warning message should be shown.

**Comment by bionade24** [comment]
> * We should use this method only as backup if other methods fail, since it doesn't necessarily show the version of the actually installed package (e.g. user hasn't done an upgrade recently). Additionally, a warning message should be shown.

If it should be the backup method, is a matter of opinion. I would use the backup only for packages not installed via package managers. Afaik most package managers can display the version in the repo database and the one installed locally. For `pacman` that would be `pacman -Si`(database) vs. `pacman -Qi`(query local pkgs). I tried to find an equivalent for `apt`, but `apt show` doesn't seem to show the installed version, but `apt list --installed` does show the installed ones and maybe the [apt-show-versions](https://packages.debian.org/jessie/apt-show-versions) package would also be an option to query from.

**Comment by bit101** [comment]
Interesting idea. Looks like this would work:

`pacman -Si $1 | sed -Ene 's/^Version\W*: (.*)/\1/p'`

**Comment by bit101** [comment]
`pacman -Qi` works pretty well and gives an error if the package is not installed. So that's nice. Could work well as a backup

**Comment by bit101** [comment]
so basically...

```if (tool is not in the list):
	if (pacman is installed):
		result = pacman -Qi tool
		if (no error):
			return result sed ...
		else:
			can check pacman -Si here to determine if A. not known, or B. known but not installed.
			return "i don't know about this one or it is not installed."
	else if (apt is installed):
		result = tbd...
		etc. similar to above
```

**Comment by bit101** [comment]
apt list --installed | sed -Ene 's/^xauth\/[^ ]* ([^ ]+) .*/\1/p'
might work

**Comment by bit101** [comment]
Actually, you can name the package you are looking for too...

	apt list $1 --installed | sed -Ee 's/^[^ ]* ([^ ]*) .*/\1/'

Makes the regex simpler.

**Comment by bit101** [comment]
Made a branch. Seems like the pacman option is pretty much working.

https://github.com/bit101/version/tree/packages

**Comment by bit101** [comment]
have apt pretty much working too.

**Comment by bit101** [comment]
pull request: https://github.com/bit101/version/pull/34

**Comment by bit101** [comment]
https://github.com/bit101/version/blob/packages/testplan.md

**Comment by bit101** [comment]
merged

**Comment by bit101** [comment]
I'll look into DNF later.
